import '~/styles/globals.css'

import { GeistSans } from 'geist/font/sans'

import { cookies } from 'next/headers'

import { TRPCReactProvider } from '~/trpc/react'
import { ThemeProvider } from './_components/shared/theme-provider'
import { type Metadata } from 'next'

export const metadata = {
  title: 'Mobility',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
} satisfies Metadata

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`font-sans ${GeistSans.variable}`}>
        <ThemeProvider>
          <TRPCReactProvider cookies={cookies().toString()}>{children}</TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
